name: download
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.9.13
  - pip=22.2.2
  - cudatoolkit=9
  - pytorch=1.11.0
  - torchvision=0.12.0
  - numpy=1.19.2
  - pip:
    - requests==2.28.1
    - flickrapi==2.4.0
    - icrawler==0.6.6
